ALTER TABLE CONTRACTOR
ADD CONTACT_PERSON VARCHAR(50)
;
ALTER TABLE ORDER_DOC
ADD IS_CASH NUMERIC(1,0)
DEFAULT 1
;
ALTER TABLE ORDER_DOC
ADD PLAN_DATE_PAY DATE
;
ALTER TABLE SPR_TYPE_ORDER
ADD IS_NO_COMP NUMERIC(1,0)
DEFAULT 0
;
ALTER TABLE ORDER_DOC
ADD SUM_WO_DISCOUNT NUMERIC(12,2)
DEFAULT 0
;
