INSERT INTO SPR_MEASURE (ID_SPR_MEASURE, NAME_MEASURE, NAME_MEASURE_SHORT, NAME_MEASURE_PRICE, NAME_MEASURE_PRICE_SHORT, KOEF_PRICE)
                 VALUES (2, 'штука', 'шт', 'штука', 'шт', 1);
INSERT INTO SPR_MEASURE (ID_SPR_MEASURE, NAME_MEASURE, NAME_MEASURE_SHORT, NAME_MEASURE_PRICE, NAME_MEASURE_PRICE_SHORT, KOEF_PRICE)
                 VALUES (3, 'штука', 'шт', '10 штук', '10 шт', 10);
INSERT INTO SPR_MEASURE (ID_SPR_MEASURE, NAME_MEASURE, NAME_MEASURE_SHORT, NAME_MEASURE_PRICE, NAME_MEASURE_PRICE_SHORT, KOEF_PRICE)
                 VALUES (4, 'штука', 'шт', '100 штук', '100 шт', 100);
INSERT INTO SPR_MEASURE (ID_SPR_MEASURE, NAME_MEASURE, NAME_MEASURE_SHORT, NAME_MEASURE_PRICE, NAME_MEASURE_PRICE_SHORT, KOEF_PRICE)
                 VALUES (5, 'штука', 'шт', '1000 штук', '1000 шт', 1000);
INSERT INTO SPR_MEASURE (ID_SPR_MEASURE, NAME_MEASURE, NAME_MEASURE_SHORT, NAME_MEASURE_PRICE, NAME_MEASURE_PRICE_SHORT, KOEF_PRICE)
                 VALUES (6, 'погонный метр', 'п. метр', 'погонный метр', 'п. метр', 1);
INSERT INTO SPR_MEASURE (ID_SPR_MEASURE, NAME_MEASURE, NAME_MEASURE_SHORT, NAME_MEASURE_PRICE, NAME_MEASURE_PRICE_SHORT, KOEF_PRICE)
                 VALUES (7, 'метр', 'м', 'метр', 'м', 1);
INSERT INTO SPR_MEASURE (ID_SPR_MEASURE, NAME_MEASURE, NAME_MEASURE_SHORT, NAME_MEASURE_PRICE, NAME_MEASURE_PRICE_SHORT, KOEF_PRICE)
                 VALUES (8, 'квадратный метр', 'м2', 'квадратный метр', 'м2', 1);
INSERT INTO SPR_MEASURE (ID_SPR_MEASURE, NAME_MEASURE, NAME_MEASURE_SHORT, NAME_MEASURE_PRICE, NAME_MEASURE_PRICE_SHORT, KOEF_PRICE)
                 VALUES (9, 'килограмм', 'кг', 'килограмм', 'кг', 1);
INSERT INTO SPR_MEASURE (ID_SPR_MEASURE, NAME_MEASURE, NAME_MEASURE_SHORT, NAME_MEASURE_PRICE, NAME_MEASURE_PRICE_SHORT, KOEF_PRICE)
                 VALUES (10, 'грамм', 'г', 'грамм', 'г', 1);
INSERT INTO SPR_MEASURE (ID_SPR_MEASURE, NAME_MEASURE, NAME_MEASURE_SHORT, NAME_MEASURE_PRICE, NAME_MEASURE_PRICE_SHORT, KOEF_PRICE)
                 VALUES (11, 'литр', 'л', 'литр', 'л', 1);
INSERT INTO SPR_MEASURE (ID_SPR_MEASURE, NAME_MEASURE, NAME_MEASURE_SHORT, NAME_MEASURE_PRICE, NAME_MEASURE_PRICE_SHORT, KOEF_PRICE)
                 VALUES (12, 'миллилитр', 'мл', 'миллилитр', 'мл', 1);
INSERT INTO SPR_MEASURE (ID_SPR_MEASURE, NAME_MEASURE, NAME_MEASURE_SHORT, NAME_MEASURE_PRICE, NAME_MEASURE_PRICE_SHORT, KOEF_PRICE)
                 VALUES (13, 'упаковка', 'упак', 'упаковка', 'упак', 1);

COMMIT WORK;
